ElastiCacheSubnetGroup:
  Type: AWS::ElastiCache::SubnetGroup
  Properties:
    CacheSubnetGroupName: ${self:service}-${self:provider.stage}
    Description: Created from the Serveles Service ${self:service}
    SubnetIds:
    - Ref: SubnetA
    - Ref: SubnetB
    - Ref: SubnetC